### ISSUE TITLE
Source distributions should not include docs / website

### ISSUE THREAD

**Issue by feynmanliang** [stefanwebb/flowtorch#47]
Our source distributions (https://pypi.org/project/flowtorch/0.0.dev2/#files) don't filter out the docs/website. As a result, the javascript in there is causing a Yarn validation failure internally at FB.

**Comment by stefanwebb** [comment]
Oh no! Let me make a quick fix here

**Comment by stefanwebb** [comment]
I've made a fix in the latest commit and tested it: https://github.com/stefanwebb/flowtorch/compare/136d866..a812e0f

It turns out we need to have a `MANIFEST.in` file to exclude certain files from the source distribution
