### ISSUE TITLE
Replace .event_dim with .input_event_dim + .output_event_dim

### ISSUE THREAD

**Issue by fritzo** [stefanwebb/flowtorch#9]
PyTorch distributions already [fixed this](https://github.com/pytorch/pytorch/pull/48041/files#diff-9c38272c807be20a5832ca58bc3b1f3454c70d30e28ecbd39ca40191219f7d81)

BTW can we simply replace these with `.input_event_shape` and `.output_event_shape`, or are the complete shapes unknown at time of Bijector construction?

**Comment by stefanwebb** [comment]
Could you elaborate? The complete shapes are only known when you instantiate the bijector with `new_dist, params = bijector(base_dist)`

**Comment by fritzo** [comment]
> Could you elaborate?

1. PyTorch distributions has already replaced the single attribute `Transform.event_dim` with a pair of attributes `.input_event_dim`, `.output_event_dim`. This resolves a bunch of issues regarding transforms that change the event dim, like `LowerCholeskyTransform`.
2. I guess this is not relevant; I was thinking that if complete shapes were known then we could be even more precise...

**Comment by stefanwebb** [comment]
Closing this since we can use `Transform.domain.event_dim` from now
